Create .tool-versions
Declare the expected ruby version

Tool compatibility is important and it is useful to declare the specific versions of tooling a project expects. Version managers - like asdf - can read this and ensure that the appropriate tools are present on the host system.

The aim is to reduce friction for students and reviewers when bootstrapping an assignment / project. This adds a declaration of a compatible Ruby version; since this project uses an antiquated version of Rails, not compatible with Ruby 3.x.

```
== Installing dependencies ==
The Gemfile's dependencies are satisfied

== Preparing database ==
Created database 'db/development.sqlite3'
Created database 'db/test.sqlite3'
rails aborted!
ArgumentError: wrong number of arguments (given 3, expected 2)
.....rails-assessment-one/config/environment.rb:5:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
(See full trace by running task with --trace)
```